### ISSUE TITLE
Support for runtime debian-x86

### ISSUE THREAD

**Issue by latop2604** [ah-/librdkafka-package#1]
Currently the latest nuget package (0.9.1) contains only :
 - debian-x64
 - osx
 - rhel-x64
 - win7-x64
 - win7-x86

Debian-x86 is missing.

I would like to be able to create a docker image based on microsoft/dotnet:latest image.
Thx.

**Comment by ah-** [comment]
Hi,

The simplest way would be to just install/build a 32 bit librdkafka and install that system-wide, especially if you're using docker anyways. rdkafka-dotnet will fall back to the system-wide librdkafka.so if it can't find a bundled one for the platform.

Alternatively you could try extending https://github.com/ah-/librdkafka-build/blob/master/build.sh to also build a 32 bit debian library and send a PR. It's probably not too hard if you just base it on a 32 bit debian docker image similar to how the RHEL/CentOS build is done.
